
import { type Listing } from "./types";

export const mockListings: Listing[] = [
  {
    listingId: "1",
    landlordId: "landlord1",
    title: "Cozy bedroom in downtown apartment",
    description: "Beautiful room in a modern apartment with great city views. Close to public transport and shopping centers. Perfect for young professionals.",
    price: 800,
    location: "Downtown",
    amenities: ["WiFi", "Parking", "Laundry", "Kitchen Access", "Air Conditioning"],
    images: [],
    createdAt: "2024-01-15",
  },
  {
    listingId: "2",
    landlordId: "landlord2", 
    title: "Spacious studio near university",
    description: "Modern studio apartment perfect for students. Includes all utilities and furnished. Walking distance to campus and local amenities.",
    price: 600,
    location: "University District",
    amenities: ["WiFi", "Furnished", "Utilities Included", "Study Area"],
    images: [],
    createdAt: "2024-01-20",
  },
  {
    listingId: "3",
    landlordId: "landlord1",
    title: "Private room with garden view",
    description: "Quiet room in a shared house with beautiful garden. Great for someone looking for a peaceful environment while still being close to the city.",
    price: 700,
    location: "Suburbs",
    amenities: ["Garden Access", "WiFi", "Parking", "Quiet Area", "Pet Friendly"],
    images: [],
    createdAt: "2024-01-25",
  },
  {
    listingId: "4",
    landlordId: "landlord3",
    title: "Modern loft in arts district",
    description: "Trendy loft space in the heart of the arts district. High ceilings, exposed brick, and plenty of natural light. Perfect for creatives.",
    price: 1200,
    location: "Arts District",
    amenities: ["High Ceilings", "Natural Light", "WiFi", "Parking", "Creative Space"],
    images: [],
    createdAt: "2024-02-01",
  },
  {
    listingId: "5",
    landlordId: "landlord2",
    title: "Affordable room near transit",
    description: "Budget-friendly option with easy access to public transportation. Basic amenities provided, perfect for those looking to save money.",
    price: 450,
    location: "Transit Hub",
    amenities: ["WiFi", "Public Transport", "Basic Furnishing", "Shared Kitchen"],
    images: [],
    createdAt: "2024-02-05",
  },
];
